server:
  port: 8008

eureka:
  instance:
    hostname: shuihu-register-center
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8008/eureka/
