server:
  port: 8003

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shuihu?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
#    password: 12345687
    password: 1993722libo
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML5
  mvc:
    format:
      date-time: yyyy/MM/dd HH:mm:ss
  application:
    name: inner-manage
  redis:
    database: 0
    password: 123456
    host: 192.168.30.102
    port: 6379

mybatis:
  mapper-locations: classpath:/mapper/**.xml

eureka:
  instance:
    instance-id: inner-manage-8003
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8008/eureka/
